---
- name: Create PostgreSQL users
  postgresql_user:
    name:             "{{item.username}}"
    password:         "{{ item.password | default(omit) }}"
    encrypted:        "{{ item.encrypted | default(omit) }}"
    role_attr_flags:  'SUPERUSER,CREATEDB'
    port:             "{{postgresql_port}}"
    state:            present
    login_user:       "{{postgresql_admin_user}}"
  become:       yes
  become_user:  "{{postgresql_admin_user}}"
  with_items:   "{{postgresql_users}}"
  when:         postgresql_users|length > 0
